### ISSUE TITLE
Is host:container socket binding secure?

### ISSUE THREAD

**Issue by dm17** [buchdag/letsencrypt-nginx-proxy-companion-compose#3]
I saw this thread ranting about how it is a bad idea:
https://news.ycombinator.com/item?id=17983623

What is your latest recommendation for using a letsencrypt/nginx companion for a bunch of services in a docker-compose.yaml? The "two container" compose file is about a year older than the 3 container one... What's the latest recommended way?
Thanks!

**Comment by dm17** [comment]
Also, is there a reason you're using "image: nginx" instead of jwilder's for the nginx-proxy? Seems like the project this is based on doesn't use that image ever.

**Comment by buchdag** [comment]
> I saw this thread ranting about how it is a bad idea:
> https://news.ycombinator.com/item?id=17983623

That's an awful lot of rant for exactly zero alternative / better solution proposed.

The fact is that `docker-gen` and `letsencrypt-nginx-proxy-companion` **require** access to the Docker daemon to work (both needs to have read access to container informations, and the latter need to restart, send SIGHUP to or execute custom commands inside another container). Whether they access the Docker daemon via a bind mounted socket, HTTPS with certs or SSH, the end result is the same, the container have access to the Docker daemon and anyone gaining access to the container gains access to the Docker Daemon too which is basically equal to being root.

The only real security improvement would be to use a [Docker authorization plugin](https://docs.docker.com/engine/extend/plugins_authorization/) on the host to restrain the Docker API capability of the containers, but that's a way more complex setup and our happy ranter himself acknowledge that "nobody uses authorization plugins" and that he wouldn't even feel confident using them.

> Also, is there a reason you're using "image: nginx" instead of jwilder's for the nginx-proxy? Seems like the project this is based on doesn't use that image ever.

[The three containers setup does not use `jwilder/nginx-proxy`.](https://github.com/jwilder/nginx-proxy#separate-containers)

**Comment by buchdag** [comment]
> The "two container" compose file is about a year older than the 3 container one...

The three containers files are only more recent because of [this commit](https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/commit/8d04cd8775aa63ef212e3b5d40e825d1a6929e81), which does not apply to two containers setup at all.

**Comment by dm17** [comment]
> > I saw this thread ranting about how it is a bad idea:
> > https://news.ycombinator.com/item?id=17983623
> 
> That's an awful lot of rant for exactly zero alternative / better solution proposed.

Agreed - if we was really such an expert, then he could suggest a better solution.

> The fact is that `docker-gen` and `letsencrypt-nginx-proxy-companion` **require** access to the Docker daemon to work (both needs to have read access to container informations, and the latter need to restart, send SIGHUP to or execute custom commands inside another container). Whether they access the Docker daemon via a bind mounted socket, HTTPS with certs or SSH, the end result is the same, the container have access to the Docker daemon and anyone gaining access to the container gains access to the Docker Daemon too which is basically equal to being root.

So the 3 container solution still has the letsencrypt container using '/var/run/docker.sock:/var/run/docker.sock' - while this solves the security issue for the nginx container:
https://github.com/jwilder/nginx-proxy/blob/master/README.md#separate-containers
You think the letsencrypt container is also OK like this?

> The only real security improvement would be to use a [Docker authorization plugin](https://docs.docker.com/engine/extend/plugins_authorization/) on the host to restrain the Docker API capability of the containers, but that's a way more complex setup and our happy ranter himself acknowledge that "nobody uses authorization plugins" and that he wouldn't even feel confident using them.
> 
> > Also, is there a reason you're using "image: nginx" instead of jwilder's for the nginx-proxy? Seems like the project this is based on doesn't use that image ever.
> 
> [The three containers setup does not use `jwilder/nginx-proxy`.](https://github.com/jwilder/nginx-proxy#separate-containers)

Except for the "jwilder/docker-gen" aspect I see in your compose file...
The nginx container seems to work with nginx:alpine - does this seem risky / less tested to you?

**Comment by buchdag** [comment]
> You think the letsencrypt container is also OK like this?

The risk is pretty much the same as running `simp_le` on the Docker host. I'm no cybersecurity expert  but to me the only attack surface is when `simp_le` communicate with the ACME server, that's not really in the same league as a publicly reachable `nginx` container.

The `letsencrypt-nginx-proxy-companion` container does not publish/expose any ports and isn't reachable from the outside.

> The nginx container seems to work with nginx:alpine - does this seem risky / less tested to you?

Not at all, I use a three containers setup with `nginx:alpine` everywhere I set it up. Works just fine.

**Comment by buchdag** [comment]
> Except for the "jwilder/docker-gen" aspect I see in your compose file...

`jwilder/nginx-proxy` is in substance `nginx` + `jwilder/docker-gen` in the same container, with `forego` for the init.

**Comment by dm17** [comment]
@buchdag Slightly off topic: would you mind posting your /etc/nginx/conf.d/default.conf relating to this setup? The default.conf is confusing and I'm guessing should be replaced... An example would help for how to map a bunch of services in docker to nginx-proxy using this default.conf.

**Comment by buchdag** [comment]
Related discussion : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/565

**Comment by buchdag** [comment]
This question has been answered, closing.
