### ISSUE TITLE
Virtual Host

### ISSUE THREAD

**Issue by basitiyidir** [buchdag/letsencrypt-nginx-proxy-companion-compose#4]
Hello,
I would host multiple sites.
I used it. (3-containers / compose-v3 / labels)
I want to put my domain.conf file under the vhost.d directory. How can I do it.

I read these. https://github.com/jwilder/nginx-proxy#per-virtual_host
I didn't get a result.

**Comment by buchdag** [comment]
Hi. Sorry but this isn't the `jwilder/nginx-proxy` repository and I can't provide support for it.
